
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: gmp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - gmp

  webserver:
    image: nginx:alpine
    container_name: gmp_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gmp

  # postgres:
  #   image: postgres:15
  #   container_name: gmp_postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: gmp_db
  #     POSTGRES_USER: gmp
  #     POSTGRES_PASSWORD: 
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - gmp

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: gmp_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - gmp

# volumes:
#   pgdata:

networks:
  gmp:
